### ISSUE TITLE
[Feature] Managed Metadata

### ISSUE THREAD

**Issue by Tiefseetauchner** [Tiefseetauchner/TiefDownConverter#19]
Add Metadata in the manifest that gets converted to tex/typst and gets added to pandoc conversions (e.g., for preprocessors).

This should be modular so it could look like:

```toml
[project_metadata]
project_name = "Title"
authors = "Steffl, Jochen, Franz"
custom_metadata = "Custom"

[metadata_settings]
command_prefix = "meta"
```

LaTeX output should define a `\meta{key}` macro that expands to `\csname meta@key\endcsname` and define each metadata value using `\expandafter\def`.

```latex
\newcommand{\meta}[1]{\csname meta@#1\endcsname}
\expandafter\def\csname meta@project_name\endcsname{Title}
\expandafter\def\csname meta@authors\endcsname{Steffl, Jochen, Franz}
```

Typst output should define a `#let meta = ()` map:

```typst
#let meta = (
  project_name: "Title",
  authors: "Steffl, Jochen, Franz",
)
```

These values should be usable in preprocessors like:

```bash
tiefdownconverter project add-preprocessor "Custom Conv" -- -o thing.html -M title="{{project_name}}"
```

Only flat string values are supported. No escaping or sanitisation is applied. Collision handling is avoided via the prefix. EPUB is excluded from this integration.

A possible future feature could allow selecting between generating `\renewcommand` statements and the dynamic `\meta{}` macro.
